# Site settings
name: Antiquarium
description: Antiquities Trade Intelligence
baseurl: ""
url: "https://www.antiquarium.io"
permalink: /:year/:month/:day/:title.html


# Build settings
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: :compressed

exclude: ['assets/_sass']
